# Generated by Django 4.2.6 on 2025-02-19 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0002_alter_orderitemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.clientmodel', verbose_name='Cliente'),
        ),
    ]
