# Generated by Django 4.2.6 on 2025-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'ordering': ['id'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='NombreCliente'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
